version: "3.9"

services:
  db:
    image: postgres:16
    container_name: devpg
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-appsecret}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5434:5432"   # host:container (5433 avoids clashing with local postgres)

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: devapp
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
      - "8888:8888"

volumes:
  pgdata:
